### ISSUE TITLE
Accuracy results

### ISSUE THREAD

**Issue by mohdwaseem27** [RnDProjectsDeebul/WaseemMohammedRnD#5]
The evaluation of the optimal PF was conducted in the turtlebot3 house simulation(default in turtlebot3 packages) with turtlebot3 burger robot. Compared with AMCL's performance, Optimal Particle Filter (PF) demonstrated higher accuracy, surpassing AMCL even with 500 particles, and notably even with only 2 or 3 particles in Optimal PF. The accuracy of AMCL standard declined as sensor noise increased, showcasing a notable trade-off between accuracy and robustness.

The experiment is done only with one environment, probably should have to check with other environments. Also this experiment is done only linear translation, have to check for rotational errors

One noteworthy thing is that, If we move the robot from directly picking and placing somewhere else, It was very hard for AMCL to relocalize itself within the environment, on the other hand optimal PF was easily localizing (Probably I will find some metrics to showcase and compare this behavior) 

![accuracy_test](https://github.com/RnDProjectsDeebul/WaseemMohammedRnD/assets/65011035/a22b0d34-87ae-4645-ac17-ee0589b1228a)

**Comment by deebuls** [comment]
Next work on the computation cost .
